### ISSUE TITLE
ShockScript

### ISSUE THREAD

**Issue by ghost** [ROBERT-MCDOWELL/Flash#4]
Compiler is now in Java again.

**Comment by Hydroper** [comment]
The Node.js version had few logical bugs in the semantic data model anyway; I already have it all in Java 13...

**Comment by Hydroper** [comment]
This is a performance comparison: [k-nucleotide](https://benchmarksgame-team.pages.debian.net/benchmarksgame/performance/knucleotide.html).

Java is position 2.3. I didn't choose C# because I need to target Android. For example, ASC 2.0 does run under Android.

**Comment by Hydroper** [comment]
I've already converted semantic data model and parsing to Java.

**Comment by Hydroper** [comment]
I've already converted semantic data model and parsing to Java.

**Comment by Hydroper** [comment]
I've just redone the verifier in JVM. I think there'll be a lot of work after codegen as well, such as API bindings... But I think API bindings can be automatically generated, fortunately.

So, for now, I'm thinking on targetting my language's own bytecode format, which does not use jump offsets. Then, after it's loadable/exportable by SXC, I can think in learning WASM or LLVM, and control flow graph.

**Comment by Hydroper** [comment]
Hey, just wanted to show some pictures:

![image](https://user-images.githubusercontent.com/52384977/77922729-cc26f000-7277-11ea-892c-7f21b212c021.png)

https://github.com/shockscript/shockscript-developer-guide/raw/master/assets/images/snippet6.png
![image](https://user-images.githubusercontent.com/52384977/77922791-e3fe7400-7277-11ea-9955-f43fbc6c2edc.png)

![image](https://user-images.githubusercontent.com/52384977/77922776-df39c000-7277-11ea-87ac-2607ab42bed1.png)

Also, the compiler is now in JVM (runs fast!). I'm stopped at codegen currently.

**Comment by Hydroper** [comment]
If you've an opinion, I'd like to hear. There's a feature based on Java 14.

![image](https://user-images.githubusercontent.com/52384977/78407146-7be2c180-75da-11ea-8f67-543c4c78cc0b.png)

In AS3 developers usually interoperate with the * type to do this stuff easily (but accessing the * type is obviously inefficient) or they do explicit casting.

**Comment by ROBERT-MCDOWELL** [comment]
Hi,

*2690*

Best Regards

LIVE-SCHOOL FOUNDATION
http://www.live-school.net
infos@live-school.net

**Comment by ROBERT-MCDOWELL** [comment]
cool
